name-template: 'v$NEXT_MINOR_VERSION'
tag-template: 'v$NEXT_MINOR_VERSION'
categories:
  - title: 'ğŸš€ Feature'
    label: 'enhancement'
  - title: 'ğŸ› Bug Fixes'
    label: 'bug'
  - title: 'ETC'
    label: 'documentation'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## Uncategorized
  $CHANGES
  ### Bump setup.py version must be included here!
